db:
  jdbcUrl: jdbc:postgresql://lunatica-pg.cv3jxdawbqpx.eu-west-2.rds.amazonaws.com:5432/postgres
  username: postgres
  password: ${DB_PASS}
  driverClassName: org.postgresql.Driver
baseUrl: http://ec2-13-41-186-167.eu-west-2.compute.amazonaws.com
