name: Build Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Build frontend app
        run: |
          cd lunatica-fe
          yarn install
          yarn build
          mkdir ../lunatica-be/app/src/main/resources/public 
          cp -R dist/* ../lunatica-be/app/src/main/resources/public

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: lunatica-be
          push: false
