name: Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Check Backend
        run: |
          cd lunatica-be
          ./gradlew app:check
          cd ..

      - name: Build and Check Frontend
        run: |
          cd lunatica-fe
          yarn install && yarn build
          cd ..
