name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Build frontend app
        run: |
          cd lunatica-fe
          yarn install
          yarn build
          mkdir ../lunatica-be/app/src/main/resources/public 
          cp -R dist/* ../lunatica-be/app/src/main/resources/public

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: AWS ECR login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t matvey-docker lunatica-be
          docker tag matvey-docker:latest 667377285515.dkr.ecr.eu-west-2.amazonaws.com/matvey-docker:latest
          docker push 667377285515.dkr.ecr.eu-west-2.amazonaws.com/matvey-docker:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop matvey-docker || true
            docker rm matvey-docker || true
            docker pull 667377285515.dkr.ecr.eu-west-2.amazonaws.com/matvey-docker:latest
            docker run -d \
              --name lunatica-app \
              -e LUNATICA_PROFILE=aws \
              -e DB_PASS=${{ secrets.RDS_DB_PASS }} \
              -p 8080:8080 \
              667377285515.dkr.ecr.eu-west-2.amazonaws.com/matvey-docker:latest

